chore(stresstest): Add better error output (#235)
Print errors with their cause so we see why requests are failing with
more information when running stresstests.

Example output:

```
ERROR: writing object
  caused by: error writing payload
  caused by: error sending request for url (http://localhost:18888/v1/objects/slow/org=0;project=0/)
  caused by: operation timed out
```